name: Build and Release Tauri App for Windows

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        with:
          args: build
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          tag_name: release-${{ github.run_number }}
          name: "Release ${{ github.run_number }}"
          files: |
            src-tauri/target/release/bundle/windows/**/*.msi
            src-tauri/target/release/bundle/windows/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}